apiVersion: v1
kind: Secret
metadata:
  name: parquimetro-secrets
  namespace: parquimetro
type: Opaque
stringData:
  JWT_SECRET: ""        # base64 de 64 bytes: openssl rand -base64 64
  ADMIN_PASS: ""
  DB_USER: parquimetro
  DB_PASS: ""
  POSTGRES_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: parquimetro-certs
  namespace: parquimetro
type: kubernetes.io/tls
data:
  ca.crt: ""      # base64 -w0 < certs/ca.crt
  server.crt: ""  # base64 -w0 < certs/server.crt
  server.key: ""  # base64 -w0 < certs/server.key
  backend.crt: ""
  backend.key: ""
