[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient@^2.8
    marcoschwartz/LiquidCrystal_I2C@^1.1.4

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DCONFIG_MBEDTLS_CERTIFICATE_BUNDLE=1

board_build.partitions = default_8MB.csv

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps = ${env:esp32dev.lib_deps}
build_flags = ${env:esp32dev.build_flags}
